### ISSUE TITLE
MCU crashes on web/mainpage refresh

### ISSUE THREAD

**Issue by balvant813** [bruxy70/Venetian-Blinds-Control#1]
I was very impressed and thankful to you after watching for you tube videos!
I downloaded and test compiled Sonoff_rolety.ino sketch. I was using nodemcu12e module to test the sketch. It compiled and uploaded  fine.  The wen interface works fine for   "/readMain",/readConfig","/pressButton","/updateField", and "/upgrade". 

BUT esp module crashes on  "/" call  and on any web page refresh! 

I did not make any changes to your code (except updating ssid, password, mqtt info etc) 

Any idea why? 

Thanks for sharing your work.
B Patel

**Comment by bruxy70** [comment]
I am sorry to hear that. I am afraid I do not have NodeMCU to test that. And it works fine on the boards I have been using. What I'd do is, I'd try disabling different parts of the page and see what is causing that. I'd start with disabling the JS readMain function, that calls XMLHttpRequest() to fill-in the values. That's probably the issue, as there is nothing special other than that.
That calls the readMain function in web.ino. I guess the problem would be somewhere there. So perhaps disabling parts of the functions and see which of them is causing it. Perhaps something with memory?
Other than that, does it do what it is supposed to do? Technically, it works even without the web, I added that one later, and you can disable it by commenting #define _WEB_ 1 in config.h.

**Comment by balvant813** [comment]
Thank you for a quick reply.

 

I will try your suggestions. 

 

I already have a DYI blind controller (based on https://github.com/thehookup/Motorized_MQTT_Blinds) with wen interface. I am trying to modify it using some of your idea (e.g. sun position and blade angle, web interface etc.). It will be very helpful to see your main web page. 

 

1.	Will it be possible to send me a link to a  .bin file compiled in Audrino IDE by using Nodemcu 1.0 (esp-12E Module) board?
2.	In my DYI project, I added motors etc. to a dumb window blind. In your case, you are controlling smart blinds by simply controlling the duration of the  power to the power supply unit provided by the blind manufacturer, correct?
3.	I have recently started using vscode and love it. But I had to put everything in one .ino file.  Do you use vscode for compiling .ino files? I see a  .vscode folder in your project, how it is used?
4.	How is .ino, .py , appdaemon objects integrated?

 

Please answer these questions at your leisure and convenience.

 

Thanks,

B Patel

**Comment by balvant813** [comment]
Hello,

 

Following changes in web.h file, solved the problem.

 

 const char MAIN_page[] PROGMEM = R"#(‘

To:

     const char MAIN_page[] = R"#(

 

I not sure if there are settings in Audrino IDE to set/check PROGMEM.

 

Thanks

 

Balvant Patel

**Comment by bruxy70** [comment]
No idea why. I thought that the PROGMEM directive just saves the string in the flash memory, instead of the RAM. There is nothing special you set-up in Arduino IDE for that. And it is weird that the other pages use the same, and they have no issues.
I guess it gets down to testing it on different boards. Anyhow, thanks for that, I have updated that in the repository, I guess it should help others too. Thanks for help.
