### ISSUE TITLE
Code not compiling properly

### ISSUE THREAD

**Issue by qasimahmed565** [bruxy70/Venetian-Blinds-Control#2]
Hello. I'm just staring out in programming and decided to upload this firmware to a sonoff 4ch I had lying around.
the issue is that I'm unable to compile the code successfully in Arduino IDE. I have all the libraries and installed everything as you have suggested in your YouTube video but still it gives an error about the <esp8266WebServerSecureAxTLS.h> and <esp8266WebServerSecureBearSSL.h> files.
commenting out these two libraries solves the issue but I cant access the webpage created by sonoff.
I also do not have the No SPIFFS options in the board settings. 
I would be extremely thankful if you can figure out the issue.

**Comment by bruxy70** [comment]
I have tested again, and on my PC it compiles smoothly, no errors.
I use esp8266 v 2.5.0. Can you try with this version?
Then I also use ArduinoJson: 5.13.4
There are newer versions, but this is what I used at the time I made it. And I am afraid that especially the board might not be properly supporting new versions.

**Comment by qasimahmed565** [comment]
downgrading the esp8266 from 2.6.3 to 2.5.0 fixed the issue.
thanks alot!!
there is one improvement that could be made which is that if the blind is fully open or fully closed then that respective button could be disabled. For example if the blind is fully open then pressing the open button should do nothing whereas as of now it still turns on the relay for a few seconds.

other than that it is a great code offering much better features than tasmota.
