### ISSUE TITLE
Support for ESP32

### ISSUE THREAD

**Issue by Zufan81** [bruxy70/Venetian-Blinds-Control#3]
Hi Vaclav,

thank you for providing such a perfect firmware for controlling venetian blinds. I have found good product from sonoff called dualR3, which has two relays, two inputs for buttons and it can monitor the power consumption. But i would like to use it for controlling blinds. One issue is that it has inside ESP32 and it cannot work with your code. Is it possible make another version that would be prepared for ESP32?

Thanks a lot.

**Comment by bruxy70** [comment]
I think it should be possible, even though I have never tried that. If you like to play with it, give it a try, and if it works please submit a PR that would support both.

OTOH, if you care about my personal advice, there might be other alternatives today that might be easier to do (that did not exist at the time I did this). Fibaro makes nice shutter actuators, that look to do exactly what they should. Or if I'd decide to make a custom one, I'd check ESP Home....

**Comment by bruxy70** [comment]
Updated, now based on ESPHome, and that works on ESP32. Check the README file. Very simple. A video with this one coming this week. Let me know if it works, if this is still the thing...
