### ISSUE TITLE
Tilting for longer time than in configuration.

### ISSUE THREAD

**Issue by pawelma** [bruxy70/Venetian-Blinds-Control#5]
Hello.
Thanks for the great extension.
I just installed it and testing with my blinds, and it works awesome, but there is one caveat with tilting.
My tilt time is around `2100` ms, but from HA it takes around `2800`. 
So to make it work, I need to select around 70% of the slider to perform the full 180* flip, without opening. 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/1849200/198845022-4fbd40fe-a33c-46bc-878e-0ba847bf12b5.png">
When selecting non corner position, my logs show difference between cover start and stop in milliseconds, and it's similar to the config that is set up (around `2100`).

Does HA send tilt position to ESP and then ESP loop take over to monitor the tilt, or could that be related with network lag?
Is there any config how to decrease 'loop sleep' interval If ESP is handling the tilt position?

**Comment by pawelma** [comment]
I guess it might be caused by adding `+1` to tilt position `%` on the time `>=`  https://github.com/bruxy70/Venetian-Blinds-Control/blob/master/components/venetian_blinds/venetian_blinds.cpp#L68
Maybe Time based cover approach would work better in that case (If I'll have some time I'll try to refactor) https://github.com/esphome/esphome/blob/e5b8dd7f2d596ff820314b61dee8848b6fe4ea7f/esphome/components/time_based/time_based_cover.cpp#L164.

**Comment by bruxy70** [comment]
I think I will leave it for now. There are at least two issues reported with it. So I'd leave the two for the time being. People can use one or the other by changing the ref.
I use them in my house for some time now. It seems to work, but I have noticed that the position does not update whilst the blinds move. Not a big deal, for this kind of blinds I use wither 0 or 100, and control the light by the tilt. But interesting nevertheless.
